# Generated by Django 2.2.10 on 2021-10-01 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1',
            name='liked_blog_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users1',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 10, 6, 13, 417306)),
        ),
    ]
